//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Settings.rc
//
#define IDC_MYICON                      2
#define IDD_SETTINGS_DIALOG             102
#define IDS_APP_TITLE                   103
#define IDD_DISPLAY                     104
#define IDD_HOTKEYS                     105
#define IDD_ABOUT                       106
#define IDD_HOTKEYPROMPT                107
#define IDD_GENERAL                     108
#define IDC_SETTINGS                    109
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       129
#define IDI_SETTINGS                    129
#define IDI_ICON2                       132
#define IDI_MAINICON                    132
#define IDD_OSD                         134
#define GRP_BEHAVIOR                    1000
#define CHK_STARTUP                     1001
#define LBL_DISPLAYDEV                  1001
#define CHK_SOUNDS                      1002
#define LBL_HIDEDELAY                   1002
#define CHK_NOTIFY                      1003
#define LBL_HIDESPEED                   1003
#define IDC_CHECK1                      1004
#define CHK_ARG                         1004
#define CHK_SHOWSTARTUP                 1004
#define CHK_BRIGHTICON                  1004
#define CMB_ARG                         1005
#define CMB_ANIMATION                   1005
#define CHK_NOTIFY2                     1005
#define CHK_EJECTICON                   1005
#define IDC_BUTTON1                     1006
#define BTN_ARG                         1006
#define CHK_VOLICON                     1006
#define CHK_ONTOP                       1007
#define CHK_FULLSCREEN                  1008
#define CHK_EJECTICON2                  1008
#define CHK_KEYICON                     1008
#define SP_DELAY                        1009
#define SP_HIDEDELAY                    1009
#define ED_DELAY                        1010
#define ED_HIDEDELAY                    1010
#define CMB_MONITOR                     1011
#define ED_SPEED                        1012
#define ED_HIDESPEED                    1012
#define SP_SPEED                        1013
#define SP_HIDESPEED                    1013
#define CMB_POSITION                    1014
#define GRP_VISIBILITY                  1015
#define GRP_POSITION                    1016
#define CMB_AUDIOTAPER                  1016
#define GRP_ANIMATION                   1017
#define GRP_EDITOR                      1018
#define CHK_DIRECTX                     1018
#define LBL_ACTION                      1019
#define ED_CUSTOMVOL                    1020
#define ED_CUSTOMX                      1020
#define ED_ARG                          1020
#define IMG_ICON                        1020
#define CMB_LANG                        1021
#define ED_CUSTOMY                      1021
#define LBL_TITLE                       1021
#define LBL_COPYRIGHT                   1022
#define LBL_LICENSE                     1023
#define CMB_SKIN                        1024
#define GRP_SKIN                        1025
#define GRP_LANGUAGE                    1026
#define CHK_MONITORVOL                  1026
#define CHK_SUBSCRIBEVOL                1026
#define LBL_AUTHOR                      1027
#define CHK_FORCELIMIT                  1027
#define SLD_LIMITER                     1028
#define ED_AUDIOTAPER                   1029
#define BTN_WEBSITE                     1030
#define BTN_WEBSITE2                    1031
#define CHK_MUTELOCK                    1031
#define LST_KEYS                        1036
#define BTN_REMOVE                      1038
#define CMB_AUDIODEV                    1038
#define BTN_ADD                         1039
#define ED_EDGE                         1039
#define LBL_AUDIODEV                    1039
#define LBL_CUSTOMX                     1040
#define CHK_ENABLECAPS                  1040
#define LBL_CUSTOMY                     1041
#define CHK_ENABLEMK                    1041
#define CHK_EDGE                        1042
#define LBL_AUDIOTAPER                  1042
#define SP_EDGE                         1043
#define CHK_MONITOREJECT                1043
#define CHK_SUBSCRIBEEJECT              1043
#define BTN_KEYS                        1044
#define LBL_LIMTER                      1044
#define LBL_LIMITER                     1044
#define CMB_ACTION                      1045
#define CHK_ENABLENUM                   1045
#define CHK_ENABLESCROLL                1046
#define LBL_KEYS                        1047
#define LBL_PROMPT                      1047
#define LBL_LIMIT                       1047
#define LBL_LIMITVAL                    1047
#define LBL_ARG                         1048
#define GRP_VOLUME                      1048
#define GRP_EJECT                       1049
#define IDC_LIST1                       1051
#define LST_OSDS                        1051
#define GRP_BRIGHTNESS                  1052
#define BTN_CANCELKEYS                  1053
#define CHK_AVOIDPRIMARY                1054
#define CHK_ENABLEVOSD                  1055
#define LBL_MONITORTARGET               1057
#define CMB_MONITORTARGET               1058
#define IDC_STATIC                      -1
#define LBL_XML                         -1
#define GRP_UPDATES                     -1
#define GRP_KEYBOARD                    -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
